# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_deunicode_wrappers", use_symbols = TRUE, package_name = "deunicode")

#' @usage NULL
#' @useDynLib deunicode, .registration = TRUE
NULL

#' Transliterates Unicode strings to ASCII
#'
#' This is a wrapper around rust crate 'deunicode':
#' https://docs.rs/deunicode/latest/deunicode/
#'
#' @param x character vector
#'
#' @return modified character vector
#' @export
#'
#' @examples
#' deunicode(c("näme1",
#'             "næme2",
#'             "北亰",
#'             "げんまい茶",
#'             "🦄☣",
#'             "…",
#'             "ᔕᓇᓇ"))
deunicode <- function(x) .Call(wrap__deunicode, x)


# nolint end
