# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_deunicode_wrappers", use_symbols = TRUE, package_name = "deunicode")

#' @usage NULL
#' @useDynLib deunicode, .registration = TRUE
NULL

deunicode <- function(x) .Call(wrap__deunicode, x)


# nolint end
